
node {
    def app
    
    stage('Clone repository') {
        git url:'https://github.com/leandrodma/juice-shop.git'
    }

    stage('Build image') {
        app = docker.build("leandrodma/juice-shop")
    }

    stage('Test image') {
        app.inside {
            sh 'echo "Tests passed"'
        }
    }

    stage('Push image') {
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            app.push("juice-${env.BUILD_NUMBER}")
        }
    }
}